 /*A use case is taken here for employee data and this is a class generated by Project L if he wnts to create a super class and want to overriding on his methods 
which are created in super class i.e abstract class*/
public abstract class DemoDynDispEm {
	int empId;
	String empName;
	public DemoDynDispEm() {
	
		// TODO Auto-generated constructor stub
	}
	public DemoDynDispEm(int empId, String empName) {
		
		this.empId = empId;
		this.empName = empName;
	}
	 void dipEmpDetails() {
		 System.out.println("emp details are "+empId +" "+ empName);
	 }
	 //creating an abstract method so that the class mandatorily have an abstract keyword
	 abstract int calSal();

}


//creating a child class

class RegEmp extends DemoDynDispEm{
	int bSal=15000;

	public RegEmp() {
		super();
		// TODO Auto-generated constructor stub
	}
//creating overloaded constructor for reg employee i.e child class
	public RegEmp(int empId, String empName,int bSal) {
		//here the super should be the first statement and constructor is taken here
		super(empId, empName);
		// TODO Auto-generated constructor stub
		this.bSal=bSal;
	}
	//the abstract method should be create here by taking from abstract class
	int calSal() {
		int hra=(15*bSal)/100;
		int ca=(13*bSal)/100;
		return(bSal+hra+ca);
	}
	
	
	
}



class CtrEmp extends DemoDynDispEm{
	CtrEmp(){}
	
	public CtrEmp(int empId, String empName) {
		super(empId, empName);
		// TODO Auto-generated constructor stub
	}

	//Overriding method
	int calSal() {
		return 10000;
	}
	
} 